### PR TITLE
Display complete parent folder path

### PR DESCRIPTION
**Pull request by TimNZ**
Append complete parent folder path
Use select2 matcher to only search on child folder name

### CODE REVIEW

**Comment by TimNZ** [comment]
screen shot 2017-08-09 at 8 54 34 am

**Comment by TimNZ** [comment]
Increased max height of popup, too small currently.

screen shot 2017-08-09 at 9 09 00 am

**Comment by wasserth** [comment]
Nice feature. Thanks. I will test it and then merge it.

**Comment by TimNZ** [comment]
I made some other mods, got a couple more I want  to do.
Will push these next week.

In the screenshot version below:
* Many times I want to create a new subfolder for a bookmarm
-> It does stop instant bookmarking when an existing folder is selected, but that could made a simple option
* Make it easy to launch Bookmark tab as sometime you just need to go in there if you decide you need to do some organising before bookmarking :)


screen shot 2017-09-23 at 11 46 22 am

**Pull request merged**
